apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:  
  name: alow-port-80
  namespace: default
spec:
  ingress:
  - from:
    ports:
     - port: 80
       protocol: TCP
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
  - Ingress
